### ISSUE TITLE
PIC ON VSC

### ISSUE THREAD

**Issue by ahmed-esmail** [Redouane64/PIC-on-VSCode#7]
please more details  about this beacuse i can't run it and i have xc8 compiler

**Comment by Redouane64** [comment]
Sorry for delay to write back.

Can you specify what is your problem exactly?

Anyways for troubleshooting, Make sure `%XC_DIR%` environment variable is set. It must point to XC8 compiler directory.

**Comment by ahmed-esmail** [comment]
yes it is set 
i have to change the path in the 

> c_cpp_properties

 file ???

**Comment by ahmed-esmail** [comment]
change it to my path because i used  v2.10 but there is error
![Annotation 2020-01-06 222306](https://user-images.githubusercontent.com/51207001/71846426-34c85b80-30d3-11ea-9ba5-509e91a56979.png)

**Comment by AlanTamez** [comment]
If you are using v2.10 use the path "...../Microchip/xc8/v2.10/pic/include/*" and I also change the intelliSenseMode to clang-x64. I did  that and it works
