### ISSUE TITLE
Can i use it with PIC C Compiler (CCS)

### ISSUE THREAD

**Issue by mscteck** [Redouane64/PIC-on-VSCode#9]
As the title sugest, i use PCW and would like to apply your config files. What do i have to change for that?

**Comment by Redouane64** [comment]
thanks for asking.

To use CCS compiler, you will have to change configuration in:

https://github.com/Redouane64/PIC-on-VSCode/blob/master/.vscode/c_cpp_properties.json

to point to your ccs compiler includes.

And also change:
https://github.com/Redouane64/PIC-on-VSCode/blob/460a4efca05716b889e8cdf7bdf0f3b1ab086911/Build.cmd#L4 

to your ccs compiler program path with the correct arguments & flags.

same goes for https://github.com/Redouane64/PIC-on-VSCode/blob/master/Build-Samples.cmd file
